// Auto-generated by facility/gen_facilityregister.py -- do not edit.

#include "facilityhooks.h"

namespace pvxs { namespace ioc { namespace facility {

void registerAlarmmsg();

void registerFacilities()
{
    registerAlarmmsg();
}

}}} // pvxs::ioc::facility
